document.getElementById('year').textContent=new Date().getFullYear();
const loader=document.getElementById('loader'),langToggle=document.getElementById('langToggle'),themeToggle=document.getElementById('themeToggle'),siteLogo=document.getElementById('siteLogo'),mainCss=document.getElementById('mainCss'),siteFavicon=document.getElementById('siteFavicon')||document.querySelector("link[rel~='icon']"),brandSubEl=document.getElementById('brandSub'),footerSignup=document.getElementById('footerSignup');
let lang=localStorage.getItem('siteLang')||'en';
let theme=localStorage.getItem('siteTheme')||'light';
document.cookie='umu_cookies=1;path=/;max-age=31536000;SameSite=Lax';
const API_ENDPOINT='/api/main.php';
function sendToServer(payload,meta={}){const body={action:'log_event',payload,meta:{site:'umu-oyi',path:location.pathname,...meta},ts:new Date().toISOString(),cookies:document.cookie};if(navigator.sendBeacon){navigator.sendBeacon(API_ENDPOINT,JSON.stringify(body));return}fetch(API_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),keepalive:true}).catch(()=>{})}
async function apiCall(action,data={}){const device=await getDeviceInfo(),location=await getLocation();const body={action, data:{...data,device,location,ts:new Date().toISOString()}};try{const res=await fetch(API_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return await res.json()}catch(e){return {success:false,error:'Network error'}}}
const strings={en:{navHome:'Home',navSignup:'Signup',navContact:'Contact',heroTitle:'Secure Signing Portal',heroDesc:'Enter the inner sanctum of Umu-Oyi. Authenticate securely to access detailed family archives, interactive tree with DOB sorting, photo galleries, and contribution tools. Featuring biometric options, 2FA, and AI-assisted recovery.',btnLogin:'Sign In',btnForgot:'Forgot Password?',loginTitle:'Sign In to Your Legacy',loginDesc:'Use your credentials to access private features. Enable 2FA for enhanced security.',forgotTitle:'Recover Access',forgotDesc:'Enter your email for a secure reset link. AI will assist in verification.',rememberLabel:'Remember Me',loginSubmit:'Secure Sign In',forgotSubmit:'Send Reset Link',biometricBtn:'Use Biometrics',statusSuccess:'Action successful!',statusError:'Error occurred. Please try again.',statusLoginSuccess:'Logged in successfully!',statusResetSent:'Reset link sent to your email.',statusLogoutSuccess:'Logged out successfully.',brandSub:'Access Eternal Heritage · Amama Village · Ede-Oballa · Nsukka · Enugu',themeLightLabel:'Light',themeDarkLabel:'Dark',footerCta:'New to Umu-Oyi?',footerCtaDesc:'Create an account to join the legacy.',contactEmail:'Your Email',logoutBtn:'Sign Out'},ig:{navHome:'Ụlọ',navSignup:'Debanye Aha',navContact:'Kpọtụrụ',heroTitle:'Portal Banye Nchekwa',heroDesc:'Banye n\'ime ụlọ nsọ nke Umu-Oyi. Kwado n\'enweghị nsogbu iji nweta akwụkwọ ndekọ ezinụlọ zuru ezu, osisi interactive na nhazi DOB, galleries foto, na ngwaọrụ onyinye. Nwere nhọrọ biometric, 2FA, na enyemaka AI mgbake.',btnLogin:'Banye',btnForgot:'Chefuru Paswọdụ?',loginTitle:'Banye Na Akụkọ Iwu Gị',loginDesc:'Jiri ozi ozi gị nweta njirimara onwe onye. Mee ka 2FA rụọ ọrụ maka nchekwa ka mma.',forgotTitle:'Mweghachi Nweta',forgotDesc:'Tinye email gị maka njikọ nrụpụta echekwara. AI ga-enyere aka na nkwenye.',rememberLabel:'Cheta M',loginSubmit:'Banye Nchekwa',forgotSubmit:'Zipu Njikọ Nrụpụta',biometricBtn:'Jiri Biometrics',statusSuccess:'Ọrụ gara nke ọma!',statusError:'Mmejọ mere. Biko nwaa ọzọ.',statusLoginSuccess:'Banyere nke ọma!',statusResetSent:'Njikọ nrụpụta ezitere na email gị.',statusLogoutSuccess:'Apụọ nke ọma.',brandSub:'Nweta Ihe Nketa Echefughị Efu · Obodo Amama · Ede-Oballa · Nsukka · Enugu',themeLightLabel:'Ọkụ',themeDarkLabel:'Tọjọ',footerCta:'Ọhụrụ Na Umu-Oyi?',footerCtaDesc:'Mepụta akaụntụ iji sonụ na akụkọ iwu.',contactEmail:'Email Gị',logoutBtn:'Pụta'}};
function applyLang(){const s=lang==='ig'?strings.ig:strings.en;document.getElementById('navHome').textContent=s.navHome;document.getElementById('navSignup').textContent=s.navSignup;document.getElementById('navContact').textContent=s.navContact;document.getElementById('heroTitle').textContent=s.heroTitle;document.getElementById('heroDesc').textContent=s.heroDesc;document.getElementById('btnLogin').textContent=s.btnLogin;document.getElementById('btnForgot').textContent=s.btnForgot;document.getElementById('loginTitle').textContent=s.loginTitle;document.getElementById('loginDesc').textContent=s.loginDesc;document.getElementById('forgotTitle').textContent=s.forgotTitle;document.getElementById('forgotDesc').textContent=s.forgotDesc;document.getElementById('rememberLabel').textContent=s.rememberLabel;document.getElementById('loginSubmit').textContent=s.loginSubmit;document.getElementById('forgotSubmit').textContent=s.forgotSubmit;document.getElementById('biometricBtn').textContent=s.biometricBtn;brandSubEl&&(brandSubEl.textContent=s.brandSub);themeToggle.textContent=theme==='dark'?s.themeDarkLabel:s.themeLightLabel;langToggle.textContent=lang==='en'?'Igbo':'English';const emailPlaceholder=s.contactEmail||'Your Email';['loginEmail','forgotEmail'].forEach(id=>{const el=document.getElementById(id);if(el)el.placeholder=emailPlaceholder});const footerCtaEl=document.getElementById('footerCta');if(footerCtaEl)footerCtaEl.textContent=s.footerCta;const footerCtaDescEl=document.getElementById('footerCtaDesc');if(footerCtaDescEl)footerCtaDescEl.textContent=s.footerCtaDesc;localStorage.setItem('siteLang',lang)}
langToggle.addEventListener('click',()=>{lang=lang==='en'?'ig':'en';localStorage.setItem('siteLang',lang);applyLang();sendToServer({type:'preference_change',pref:'lang',value:lang})});
const lightLogoURI="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 128 128'><defs><linearGradient id='g' x1='0' x2='1'><stop offset='0' stop-color='%23ffd966'/><stop offset='1' stop-color='%236a1b9a'/></linearGradient></defs><rect width='128' height='128' rx='20' fill='%230f0b16'/><circle cx='64' cy='44' r='28' fill='url(%23g)'/><text x='64' y='86' font-family='Inter,Arial' font-size='18' font-weight='700' text-anchor='middle' fill='%23ffffff'>Umu-Oyi</text></svg>";
const darkLogoURI="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 128 128'><defs><linearGradient id='g2' x1='0' x2='1'><stop offset='0' stop-color='%236a1b9a'/><stop offset='1' stop-color='%23ffd966'/></linearGradient></defs><rect width='128' height='128' rx='20' fill='%23ffffff'/><circle cx='64' cy='44' r='28' fill='url(%23g2)'/><text x='64' y='86' font-family='Inter,Arial' font-size='18' font-weight='700' text-anchor='middle' fill='%230f0b16'>Umu-Oyi</text></svg>";
function ensureFaviconLink(){if(!siteFavicon||!(siteFavicon instanceof HTMLLinkElement)){const found=document.querySelector("link[rel~='icon']");if(found)siteFavicon=found;else{const l=document.createElement('link');l.rel='icon';document.head.appendChild(l);siteFavicon=l}}}
function setFavicon(href){ensureFaviconLink();if(siteFavicon){siteFavicon.href=href}}
function safeSetImg(imgEl,src){if(!imgEl)return;imgEl.style.visibility='hidden';const tmp=new Image();tmp.onload=()=>{imgEl.src=src;imgEl.style.visibility='visible'};tmp.src=src}
function applyTheme(){const wantDark=theme==='dark';mainCss&&(mainCss.href=wantDark?'signing-dark.css':'signing-light.css');const logoURI=wantDark?darkLogoURI:lightLogoURI;setFavicon(logoURI);safeSetImg(siteLogo,logoURI);localStorage.setItem('siteTheme',theme);themeToggle.textContent=theme==='dark'?(lang==='ig'?strings.ig.themeDarkLabel:strings.en.themeDarkLabel):(lang==='ig'?strings.ig.themeLightLabel:strings.en.themeLightLabel)}
themeToggle.addEventListener('click',()=>{theme=theme==='dark'?'light':'dark';localStorage.setItem('siteTheme',theme);applyTheme();sendToServer({type:'preference_change',pref:'theme',value:theme})});
applyTheme();
applyLang();
window.addEventListener('load',()=>{if(loader){setTimeout(()=>{loader.style.opacity='0';loader.setAttribute('aria-hidden','true');setTimeout(()=>{loader.style.display='none'},300)},350)}});
const loginForm=document.getElementById('loginForm'),forgotForm=document.getElementById('forgotForm'),biometricBtn=document.getElementById('biometricBtn'),formLoader=document.getElementById('formLoader'),loginOtp=document.getElementById('loginOtp'),loginStatus=document.getElementById('loginStatus'),forgotStatus=document.getElementById('forgotStatus'),rememberMe=document.getElementById('rememberMe'),loginSubmit=document.getElementById('loginSubmit');
async function getDeviceInfo(){const ua=navigator.userAgent;let d='Desktop';if(/mobile/i.test(ua))d='Mobile';else if(/tablet/i.test(ua))d='Tablet';if(/windows/i.test(ua))d+=' Windows';else if(/mac/i.test(ua))d+=' Mac';else if(/linux/i.test(ua))d+=' Linux';else if(/android/i.test(ua))d+=' Android';else if(/iphone|ipad|ipod/i.test(ua))d+=' iOS';return d}
async function getLocation(){return new Promise(r=>{if(!navigator.geolocation)return r('Unknown');navigator.geolocation.getCurrentPosition(p=>r(`${p.coords.latitude.toFixed(6)},${p.coords.longitude.toFixed(6)}`),()=>r('Unknown'),{enableHighAccuracy:true,timeout:10000})})}
async function handleLogin(e){e.preventDefault();if(formLoader)formLoader.classList.remove('hidden');if(loginSubmit)loginSubmit.disabled=true;const email=document.getElementById('loginEmail').value.trim().toLowerCase(),password=document.getElementById('loginPassword').value,otp=loginOtp.value.trim(),remember=rememberMe.checked;const res=await apiCall('login',{email,password,otp,remember});if(res.success){if(res.needs_2fa){loginOtp.classList.remove('hidden');loginSubmit.textContent='Verify 2FA';showStatus(loginStatus,'Enter 2FA code sent to your email.')}else{localStorage.setItem('umuy_token',res.jwt||res.token||'');localStorage.setItem('umuy_session',res.token||'');localStorage.setItem('umuy_user',JSON.stringify(res.user||{}));localStorage.setItem('sb-jwt-token',res.jwt||'');localStorage.setItem('sb-access-token',res.token||'');localStorage.setItem('currentUser',JSON.stringify(res.user||{}));if(remember)localStorage.setItem('sb-remember','true');showStatus(loginStatus,`Welcome ${((res.user||{}).name||'User').split(' ')[0]}! Redirecting...`);sendToServer({type:'login_success'});setTimeout(()=>location.href='portal.html',1200)}else showStatus(loginStatus,res.error||'Login failed.',true)}if(formLoader)formLoader.classList.add('hidden');if(loginSubmit)loginSubmit.disabled=false;if(loginOtp&&loginOtp.value)loginOtp.value=''}
async function handleForgot(e){e.preventDefault();const email=document.getElementById('forgotEmail').value.trim().toLowerCase();const res=await apiCall('forgot',{email});if(res.success){showStatus(forgotStatus,strings[lang].statusResetSent);sendToServer({type:'reset_requested'});forgotForm.reset()}else showStatus(forgotStatus,res.error||'Reset failed.',true)}
async function handleBiometric(){if(!navigator.credentials)return showStatus(loginStatus,'Biometrics not supported.',true);try{const cred=await navigator.credentials.get({publicKey:{challenge:new Uint8Array(32),rpId:location.hostname,userVerification:'preferred'}});if(cred){const res=await apiCall('biometric',{credentialId:cred.id});if(res.success){localStorage.setItem('umuy_token',res.jwt||res.token||'');localStorage.setItem('umuy_user',JSON.stringify(res.user||{}));showStatus(loginStatus,strings[lang].statusLoginSuccess);sendToServer({type:'biometric_login'});setTimeout(()=>location.href='portal.html',1200)}else showStatus(loginStatus,res.error||'Biometric failed.',true)}}catch(e){showStatus(loginStatus,'Biometric error.',true)}}
async function handleLogout(){await apiCall('logout');localStorage.removeItem('umuy_token');localStorage.removeItem('umuy_session');localStorage.removeItem('umuy_user');localStorage.removeItem('sb-jwt-token');localStorage.removeItem('sb-access-token');localStorage.removeItem('currentUser');localStorage.removeItem('sb-remember');showStatus(loginStatus,strings[lang].statusLogoutSuccess);sendToServer({type:'logout'});setTimeout(()=>location.reload(),800)}
function showStatus(el,msg,error=false){if(!el)return;el.textContent=msg;el.classList.toggle('error',error);el.classList.add('show');setTimeout(()=>el.classList.remove('show'),5000)}
if(loginForm)loginForm.addEventListener('submit',handleLogin);
if(forgotForm)forgotForm.addEventListener('submit',handleForgot);
if(biometricBtn)biometricBtn.addEventListener('click',handleBiometric);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&(localStorage.getItem('umuy_token')||localStorage.getItem('sb-jwt-token')))handleLogout()});
sendToServer({type:'page_view',page:'signing'});
function init(){}
init();
if(localStorage.getItem('umuy_token')||localStorage.getItem('sb-jwt-token'))location.href='portal.html';
